export default {
  'Korea Republic': 'red',
  Germany: 'green',
  Serbia: 'red',
  'Costa Rica': 'red',
  Poland: 'red',
  Senegal: 'green',
  Panama: 'blue',
  Tunisia: 'red',
  Argentina: 'blue',
  Portugal: 'green',
  Mexico: 'green',
  Japan: 'blue',
  Colombia: 'yellow',
  England: 'red',
  Sweden: 'yellow',
  Switzerland: 'red',
  Uruguay: 'blue',
  France: 'blue',
  Brazil: 'yellow',
  Belgium: 'red',
  Spain: 'red',
  Russia: 'white',
  Croatia: 'red',
  'Saudi Arabia': 'green',
  Egypt: 'black',
  Morocco: 'red',
  Iran: 'green',
  Australia: 'yellow',
  Peru: 'red',
  Iceland: 'blue',
  Nigeria: 'green',
  Denmark: 'red',
};
